### ISSUE TITLE
Port CAN server to Python 3 Socket module

### ISSUE THREAD

**Issue by ausshir** [UofSSpaceDesignTeam/roveberrypy#15]
See: https://docs.python.org/3/library/socket.html#socket.AF_CAN

We want to potentially use the standard module for CAN and sockets rather than use a legacy library.

This is the current library: https://python-can.readthedocs.io/en/latest/

**Comment by ottopasuuna** [comment]
I found some slides from a talk for some linux conference. It's in German, but they have some code examples in C and Python.
https://glt14-programm.linuxtage.at/attachments/151_GLT2014-CANBus.pdf
May not be helpfull, but just thought I'd share.

**Comment by ausshir** [comment]
Thanks, those code examples are exactly what I was looking for.

Also enjoying the beautiful strawberry shortcake at the end! :P

**Comment by ausshir** [comment]
We are not focusing on the CAN server at this time. Closing for now - can be reopened as needed.
