### ISSUE TITLE
Read GPS positions

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceDesignTeam/roveberrypy#24]
Be able to read GPS positions from the Piksi gps units. Last year's code may have most of this implemented.

**Comment by LiamBindle** [comment]
I can give a hand with this when I get back if you guys dont have it already. It'll take only a couple minutes.

**Comment by ausshir** [comment]
GPS is actually a lower priority for ERC since it is indoors, but when you get back we should talk about the nav system!
