### ISSUE TITLE
Implement VESC packet handler

### ISSUE THREAD

**Issue by ottopasuuna** [UofSSpaceDesignTeam/roveberrypy#53]
We need a more robust way of encoding and decoding messages using the VESC communication protocol. @LiamBindle has developed a library that is almost complete (found here [https://github.com/LiamBindle/vesc](https://github.com/LiamBindle/vesc)). Once he is finished, it can be integrated into the USBServer.

- [X] get wheels spinning with library
- Add messages:
    - [X] rpm
    - [x] pwm
    - [x] current
    - [x] current_brake
- [x] properly integrate vesc library into roveberrypy code base.

**Comment by LiamBindle** [comment]
Almost ready for PyVESC v1.0.0 release. Just need a bit more testing. Also today I cleaned up the interface a bit. Also implemented the Setter's you listed above.

**Comment by ottopasuuna** [comment]
I'd say this is done. Any issues with the library its self can be done from Liam's official repo: [Pyvesc](https://github.com/LiamBindle/PyVESC/). Any new messages can be added to the USST's fork: [https://github.com/UofSSpaceDesignTeam/PyVESC](https://github.com/UofSSpaceDesignTeam/PyVESC)
